# Generated by Django 5.1.2 on 2024-11-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_options_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
