# Generated by Django 5.1.2 on 2025-05-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='complete',
        ),
    ]
